my:
  greeting: Hello World from config server

app:
   name: MyAppFromConfigServer
   description: Welcome to ${app.name}

db:
  connection: "{connectionString:  'http----config-server'}"
  host: 127.0.0.1
  port: 1200

management.endpoints.web.exposure.include: "*"
